deployment:
  name: nuska
service:
  http:
    externalPort: 8080
    internalPort: 8080

replicas: 2
rollingUpdate:
  maxSurge: 25%
  maxUnavailable: 25%

resources:
  memLimit: "1500Mi"
  cpuRequest: "2"
  memRequest: "1000Mi"
  xss: 512k
  xmx: 1000m

configMapMount:
  name: nuska-config

image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always
