apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.nuska
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.common.service.internalPort }}

    # Blobstore
    blobstore.gcs.project.id=ent-nuska-dev
    blobstore.gcs.nisaba.container.name={{ .Values.gcp.nisaba.exchangeBucketName }}

    # Actuator
    management.server.port={{ .Values.common.service.internalPort }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.health.pubsub.enabled=false

    # Logging
    logging.config=classpath:logback.xml
    logging.level.no.entur=INFO
    logging.level.no.entur.antu=INFO
    logging.level.org.apache=INFO
    logging.level.org.apache.camel.component.http.HttpComponent=WARN

    #OAuth2 Resource Server
    nuska.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/
    nuska.oauth2.resourceserver.auth0.partner.organisations={1:'RB', 14:'MOR', 20:'NSB', 22:'RUT', 35:'GOA', 41:'SJN', 56:'FLI', 23:'HUR', 58:'VYX', 59:'VYB', 68:'FAR', 29:'TRO', 74:'CON', 79:'DGR', 60:'HAV'}

    # OAuth2 Resource Server for Entur Partner tenant
    nuska.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri={{ .Values.auth0.partner.url }}
    nuska.oauth2.resourceserver.auth0.entur.partner.jwt.audience={{ .Values.auth0.partner.audience }}

    # OAuth2 Resource Server for Entur Internal tenant
    nuska.oauth2.resourceserver.auth0.entur.internal.jwt.issuer-uri={{ .Values.auth0.internal.url }}
    nuska.oauth2.resourceserver.auth0.entur.internal.jwt.audience={{ .Values.auth0.internal.audience }}

    netex.export.block.authorization={FAR:'OST,ATB,INN',CON:'TRO,BRA', DGR:'FIN'}

kind: ConfigMap
metadata:
  name: nuska-application
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nuska.common.labels" . | indent 4 }}
