apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.nuska
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.service.http.internalPort }}

    # Blobstore
    blobstore.gcs.project.id=ent-nuska-dev
    blobstore.gcs.nisaba.container.name={{ .Values.gcp.nisaba.exchangeBucketName }}

    # Actuator
    management.server.port={{ .Values.service.http.internalPort }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.health.pubsub.enabled=false

    # OPenAPI
    springdoc.api-docs.path=/api-docs

    # Logging
    logging.config=classpath:logback.xml
    logging.level.no.entur=INFO
    logging.level.no.entur.antu=INFO
    logging.level.org.apache=INFO
    logging.level.org.apache.camel.component.http.HttpComponent=WARN

    #OAuth2 Resource Server
    nuska.oauth2.resourceserver.auth0.ror.claim.namespace=https://ror.entur.io/

    # OAuth2 Resource Server for Entur Partner tenant
    nuska.oauth2.resourceserver.auth0.entur.partner.jwt.issuer-uri={{ .Values.auth0.partner.url }}
    nuska.oauth2.resourceserver.auth0.entur.partner.jwt.audience={{ .Values.auth0.partner.audience }}

    # OAuth2 Resource Server for Entur Internal tenant
    nuska.oauth2.resourceserver.auth0.entur.internal.jwt.issuer-uri={{ .Values.auth0.internal.url }}
    nuska.oauth2.resourceserver.auth0.entur.internal.jwt.audience={{ .Values.auth0.internal.audience }}

    # OAuth2 Entur Internal Client
    spring.security.oauth2.client.registration.internal.authorization-grant-type=client_credentials
    spring.security.oauth2.client.registration.internal.client-id={{ .Values.auth0.client.clientId }}
    spring.security.oauth2.client.provider.internal.token-uri={{ .Values.auth0.client.tokenUri }}
    ror.oauth2.client.audience={{ .Values.auth0.client.audience }}

    # Authorization
    nuska.security.role.assignment.extractor={{ .Values.roleAssignmentExtractor }}
    user.permission.rest.service.url={{ .Values.baba.service }}/services/organisations/users


kind: ConfigMap
metadata:
  name: nuska-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nuska.common.labels" . | indent 4 }}
