apiVersion: v1
data:
  application.properties: |+

    # Spring
    spring.main.sources=no.entur.nuska
    spring.profiles.active=gcs-blobstore
    server.port={{ .Values.common.service.internalPort }}

    # Nuska
    nuska.security.authorization-service=token-based

    # Blobstore
    blobstore.gcs.project.id=ent-nuska-dev
    blobstore.gcs.nisaba.container.name={{ .Values.gcp.nisaba.exchangeBucketName }}

    # Actuator
    management.server.port={{ .Values.common.service.internalPort }}
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.health.pubsub.enabled=false

    # Logging
    logging.config=classpath:logback.xml
    logging.level.no.entur=INFO
    logging.level.no.entur.antu=INFO
    logging.level.org.apache=INFO
    logging.level.org.apache.camel.component.http.HttpComponent=WARN

kind: ConfigMap
metadata:
  name: nuska-application
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nuska.common.labels" . | indent 4 }}
