apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: api
    {{- include "nuska.common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: timetable-data
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: timetable-data{{ .Values.ingress.domainName }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: nuska
                port:
                  number: {{ .Values.service.http.externalPort }}
