name: Build and push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  maven-verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          repository: entur/nuska
      - uses: actions/setup-java@v4
        with:
          java-version: 21.0.1+12
          distribution: liberica
          cache: 'maven'
      - run: mvn verify -DskipTests=true
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: target/*.jar
  docker-build:
    needs: [maven-verify]
    uses: entur/gha-docker/.github/workflows/build.yml@v1
    with:
      build_artifact_name: artifact
      build_artifact_path: target
      image_name: nuska
      dockerfile: Dockerfile
  docker-push:
    if: github.repository_owner == 'entur' && github.event_name == 'push'
    needs: [docker-build]
    uses: entur/gha-docker/.github/workflows/push.yml@v1
    with:
      image_name: nuska